# GSB 5544 — PA 5.1: Hierarchical Data, the JSON Data Format, and APIs — INSTRUCTOR SOLUTION

**How to use this notebook.** Each question is answered in the same five beats: **Approach** (the idea, in a
sentence or two) → **code** (complete and executed) → **What the code does** (piece by piece) → **Expected
output** → **Common mistakes** (what students actually do, and the symptom you will see on their screen).

**The one idea to keep returning to:** *decide what one row should be.* A show? A season? An episode? A cast
member? A tag? Every question in this activity is "pick the unit of the row, flatten to that unit with
`json_normalize`, then do ordinary pandas."

**Live data.** The TVMaze answers come from a live API; numbers were correct when this notebook was executed
(September 2026) and may drift slightly if TVMaze edits its records.

In [1]:
import pandas as pd

## Shows Data

First we'll work with the "Girls" shows JSON data from the reading.

In [2]:
# Fetch data from a URL
import requests
response = requests.get("https://dlsun.github.io/pods/data/tvshows.json")

import json
data_shows = response.json()

In [3]:
df_shows = pd.json_normalize(data_shows)
df_shows

,id,url,name,type,language,genres,status,runtime,premiered,officialSite,...,externals.thetvdb,externals.imdb,image.medium,image.original,network,webChannel.id,webChannel.name,webChannel.country.name,webChannel.country.code,webChannel.country.timezone
0,139,http://www.tvmaze.com/shows/139/girls,Girls,Scripted,English,"[Drama, Romance]",Ended,30,2012-04-15,http://www.hbo.com/girls,...,220411,tt1723816,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
1,722,http://www.tvmaze.com/shows/722/the-golden-girls,The Golden Girls,Scripted,English,"[Drama, Comedy]",Ended,30,1985-09-14,NaN,...,71292,tt0088526,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
2,23542,http://www.tvmaze.com/shows/23542/good-girls,Good Girls,Scripted,English,"[Drama, Comedy, Crime]",Running,60,2018-02-26,https://www.nbc.com/good-girls?nbc=1,...,328577,tt6474378,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
3,6771,http://www.tvmaze.com/shows/6771/the-powerpuff...,The Powerpuff Girls,Animation,English,"[Comedy, Action, Science-Fiction]",Running,15,2016-04-04,https://www.cartoonnetwork.com/video/powerpuff...,...,307473,tt4718304,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
4,42726,http://www.tvmaze.com/shows/42726/florida-girls,Florida Girls,Scripted,English,[Comedy],Running,30,2019-07-10,https://poptv.com/floridagirls,...,363682,tt8548870,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
5,32087,http://www.tvmaze.com/shows/32087/chicken-girls,Chicken Girls,Scripted,English,"[Drama, Children, Music]",Running,16,2017-09-05,https://www.youtube.com/playlist?list=PLVewHiZ...,...,339854,NaN,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,274.0,Brat,United States,US,America/New_York
6,33320,http://www.tvmaze.com/shows/33320/derry-girls,Derry Girls,Scripted,English,[Comedy],Running,30,2018-01-04,http://www.channel4.com/programmes/derry-girls,...,338903,tt7120662,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
7,1955,http://www.tvmaze.com/shows/1955/the-powerpuff...,The Powerpuff Girls,Animation,English,"[Action, Children, Crime]",Ended,30,1998-11-18,NaN,...,76200,tt0175058,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
8,1073,http://www.tvmaze.com/shows/1073/bomb-girls,Bomb Girls,Scripted,English,"[Drama, Romance, War]",Ended,60,2012-01-04,NaN,...,254378,tt1955311,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN
9,525,http://www.tvmaze.com/shows/525/gilmore-girls,Gilmore Girls,Scripted,English,"[Drama, Comedy, Romance]",Ended,60,2000-10-05,NaN,...,76568,tt0238784,http://static.tvmaze.com/uploads/images/medium...,http://static.tvmaze.com/uploads/images/origin...,NaN,NaN,NaN,NaN,NaN,NaN

1\. Summarize the networks represented by these shows and the number of these shows that aired on each network.

### Solution 1 — networks

**Approach.** One row per **show** is already what `df_shows` is, and the network's name was flattened into the
column `network.name`. Counting the values of one column is `value_counts()`.

In [4]:
# Orientation first: what did json_normalize give us?
print(type(data_shows), len(data_shows))          # a list of 10 shows
print(df_shows.shape)
df_shows[["id", "name", "premiered", "network.name", "webChannel.name"]]

<class 'list'> 10
(10, 35)

      id                 name   premiered     network.name webChannel.name
0    139                Girls  2012-04-15              HBO             NaN
1    722     The Golden Girls  1985-09-14              NBC             NaN
2  23542           Good Girls  2018-02-26              NBC             NaN
3   6771  The Powerpuff Girls  2016-04-04  Cartoon Network             NaN
4  42726        Florida Girls  2019-07-10              Pop             NaN
5  32087        Chicken Girls  2017-09-05              NaN            Brat
6  33320          Derry Girls  2018-01-04        Channel 4             NaN
7   1955  The Powerpuff Girls  1998-11-18  Cartoon Network             NaN
8   1073           Bomb Girls  2012-01-04           Global             NaN
9    525        Gilmore Girls  2000-10-05           The CW             NaN

In [5]:
df_shows["network.name"].value_counts(dropna=False)

network.name
NBC                2
Cartoon Network    2
HBO                1
Pop                1
NaN                1
Channel 4          1
Global             1
The CW             1
Name: count, dtype: int64

**What the code does.**
- `data_shows` is a **list** of 10 dictionaries (one per show). `pd.json_normalize` made one row per element.
- Each show's `network` is a nested *dictionary* (`{"id": ..., "name": ..., "country": {...}}`), so it was
  spread into dotted columns: `network.id`, `network.name`, `network.country.name`, …
- `value_counts()` tabulates a column. `dropna=False` keeps the missing value visible instead of silently
  dropping a show.

**Expected output.** NBC 2 and Cartoon Network 2; HBO, Pop, Channel 4, Global, The CW 1 each; and **one `NaN`**.

**Points to make in class.**
- The `NaN` is *Chicken Girls*: it is a web series, so its `network` is `null` in the JSON and its home
  (Brat) is under `webChannel.name` instead. A fuller answer: `df_shows["network.name"].fillna(df_shows["webChannel.name"])`.
- There are **two different shows called _The Powerpuff Girls_** (the 1998 original and the 2016 reboot —
  different `id`, different `premiered`). That is why Cartoon Network has 2. This matters in the next two
  questions: **group by `id`, not by `name`.**

**Common mistakes.**
- `df_shows["network"]["name"]` or `df_shows.network.name` → `KeyError`/wrong thing. After flattening, the
  column's *name* is the single string `"network.name"`; the dot is just a character. Use `df_shows["network.name"]`.
- Forgetting `dropna=False` and reporting 9 shows without noticing one vanished.
- Trying `data_shows["network"]` → `TypeError: list indices must be integers` — `data_shows` is a list; pick a
  show first (`data_shows[0]["network"]["name"]`).

2\. Find the number of seasons for each show in the data. Do this two ways: one which uses `df_shows`, and another that first flattens `data_shows` to a different data frame.

### Solution 2 — number of seasons, two ways

**Approach.** `seasons` is a **list** inside each show, so `json_normalize` left it as a list in one cell.
- **Way 1** keeps one row per show and measures each list: `len`.
- **Way 2** changes the unit of the row to the **season** (`record_path="seasons"`) and then counts rows per show.

In [6]:
# Way 1 — one row per show; the "seasons" cell holds a list, and len() of a list is its number of elements
df_shows["n_seasons"] = df_shows["seasons"].apply(len)
df_shows[["id", "name", "premiered", "n_seasons"]]

      id                 name   premiered  n_seasons
0    139                Girls  2012-04-15          6
1    722     The Golden Girls  1985-09-14          7
2  23542           Good Girls  2018-02-26          3
3   6771  The Powerpuff Girls  2016-04-04          3
4  42726        Florida Girls  2019-07-10          1
5  32087        Chicken Girls  2017-09-05          5
6  33320          Derry Girls  2018-01-04          2
7   1955  The Powerpuff Girls  1998-11-18          6
8   1073           Bomb Girls  2012-01-04          2
9    525        Gilmore Girls  2000-10-05          8

In [7]:
# Way 2 — one row per SEASON, carrying the show's id and name down onto each season row
df_seasons = pd.json_normalize(
    data_shows,
    record_path="seasons",            # the list to unpack: each season becomes a row
    meta=["id", "name"],              # fields of the parent show to keep
    meta_prefix="show.",              # seasons ALSO have "id" and "name" -> rename the show's to avoid a clash
)
print(df_seasons.shape)
df_seasons[["show.id", "show.name", "number", "premiereDate", "endDate"]].head(8)

(43, 27)

  show.id         show.name  number premiereDate     endDate
0     139             Girls       1   2012-04-15  2012-06-17
1     139             Girls       2   2013-01-13  2013-03-17
2     139             Girls       3   2014-01-12  2014-03-23
3     139             Girls       4   2015-01-11  2015-03-22
4     139             Girls       5   2016-02-21  2016-04-17
5     139             Girls       6   2017-02-12  2017-04-16
6     722  The Golden Girls       1   1985-09-14  1986-05-10
7     722  The Golden Girls       2   1986-09-27  1987-05-16

In [8]:
df_seasons.groupby(["show.id", "show.name"]).size()

show.id  show.name
139      Girls                  6
525      Gilmore Girls          8
722      The Golden Girls       7
1073     Bomb Girls             2
1955     The Powerpuff Girls    6
6771     The Powerpuff Girls    3
23542    Good Girls             3
32087    Chicken Girls          5
33320    Derry Girls            2
42726    Florida Girls          1
dtype: int64

**What the code does.**
- `.apply(len)` runs `len` on each cell of the column. The cell is a Python list of season dictionaries, so
  the result is the number of seasons.
- `record_path="seasons"` tells `json_normalize` to go *into* each show's `seasons` list and make **one row
  per season** (43 rows = 6 + 7 + 3 + 3 + 1 + 5 + 2 + 6 + 2 + 8).
- `meta=["id", "name"]` copies the show's id and name onto each of its season rows; without it you would have
  43 seasons and no idea which show each belongs to.
- `meta_prefix="show."` is **required here**: a season has its own `id` and `name`, and pandas refuses to
  create two columns with the same name.
- `groupby([...]).size()` counts rows per group — seasons per show.

**Expected output.** Girls 6 · The Golden Girls 7 · Good Girls 3 · The Powerpuff Girls (2016, id 6771) 3 ·
Florida Girls 1 · Chicken Girls 5 · Derry Girls 2 · The Powerpuff Girls (1998, id 1955) 6 · Bomb Girls 2 ·
Gilmore Girls 8. Both ways agree.

**Common mistakes.**
- Omitting `meta_prefix` → `ValueError: Conflicting metadata name id, need distinguishing prefix`. The error
  message is, for once, exactly the fix.
- `groupby("show.name")` alone → *The Powerpuff Girls* shows **9** seasons (3 + 6): two shows merged because
  they share a name. Group by the id (keep the name alongside for readability).
- `df_shows["seasons"].str.len()` happens to work on lists too, but `len(df_shows["seasons"])` returns 10 —
  the length of the *column*, not of each list.
- Using `.count()` on a column with missing values (e.g. `endDate`) under-counts; `.size()` counts rows.

3\. For each episode, find the length (number of characters) of the title. Then create summaries to answer: Which show tends to have the longest episode titles? The shortest?

### Solution 3 — episode title lengths

**Approach.** The unit is now the **episode**, which is *two* lists down: show → `seasons` → `episodes`. Give
`record_path` the path as a list. Then it is Week 4 string work (`.str.len()`) plus a grouped summary.

In [9]:
df_episodes = pd.json_normalize(
    data_shows,
    record_path=["seasons", "episodes"],   # walk into seasons, then into each season's episodes
    meta=["id", "name", "premiered"],
    meta_prefix="show.",
)
print(df_episodes.shape)
df_episodes[["show.name", "season", "number", "name"]].head()

(741, 16)

  show.name  season  number                      name
0     Girls       1     1.0                     Pilot
1     Girls       1     2.0              Vagina Panic
2     Girls       1     3.0  All Adventurous Women Do
3     Girls       1     4.0            Hannah's Diary
4     Girls       1     5.0           Hard Being Easy

In [10]:
df_episodes["title_length"] = df_episodes["name"].str.len()

(df_episodes
 .groupby(["show.id", "show.name", "show.premiered"])["title_length"]
 .agg(["count", "mean", "median", "min", "max"])
 .sort_values("mean", ascending=False)
 .round(1))

                                            count  mean  median  min  max
show.id show.name           show.premiered
1955    The Powerpuff Girls 1998-11-18         82  28.0    29.0    9   66
525     Gilmore Girls       2000-10-05        153  21.4    21.0    5   51
42726   Florida Girls       2019-07-10         10  20.4    23.0    5   30
722     The Golden Girls    1985-09-14        181  19.7    18.0    6   53
6771    The Powerpuff Girls 2016-04-04        119  16.5    14.0    5   42
32087   Chicken Girls       2017-09-05         76  16.4    13.0    5   70
23542   Good Girls          2018-02-26         26  15.5    14.5    4   49
1073    Bomb Girls          2012-01-04         19  14.4    15.0    8   21
139     Girls               2012-04-15         63  13.1    11.0    3   42
33320   Derry Girls         2018-01-04         12  12.5     9.0    8   35

In [11]:
# The extremes, to make it concrete
df_episodes.sort_values("title_length")[["show.name", "name", "title_length"]].iloc[[0, -1]]

,show.name,name,title_length
28,Girls,Flo,3
420,Chicken Girls,Birds of a Feather | Official Lyric Video | Th...,70

**What the code does.**
- `record_path=["seasons", "episodes"]` — a *list* of keys means "follow them in order". Result: 741 rows, one
  per episode.
- In `df_episodes`, the column `name` is the **episode title** (the record's own field); the show's name
  arrives as `show.name` because of the prefix.
- `.str.len()` gives the number of characters of each title (Topic 4.2).
- `.agg([...])` computes several summaries at once; reporting the mean *and* the median guards against one
  very long title distorting the picture; `count` shows how many episodes each summary rests on.

**Expected output.** Longest titles: **The Powerpuff Girls, the 1998 original (id 1955)** — mean ≈ 28
characters, median 29 (its titles are often two segments joined, e.g. "A / B"). Shortest: **Derry Girls**
(mean ≈ 12.5, median 9 — mostly "Episode 1", "Episode 2", …), with **Girls** close behind (mean ≈ 13).

**Common mistakes.**
- `record_path="episodes"` → `KeyError: 'episodes'`: episodes are not directly under a show; they live inside
  each season.
- Measuring `df_episodes["show.name"].str.len()` — the length of the *show's* name — because both are called
  "name" in the raw JSON. Look at `.head()` before computing.
- Grouping by show name only, which again blends the two Powerpuff series (and here it matters: the original
  is the longest, the reboot is mid-table).
- Answering from `max` alone: Chicken Girls has the single longest title (70 characters) but is not the show
  that *tends* to have long titles. "Tends to" asks for a centre, not an extreme.

4\. Do any cast members in the data set share a birthday with you? Who, and what show are they on? (If there isn't anyone, try a different day.)

### Solution 4 — a shared birthday

**Approach.** The unit is the **cast member** (`record_path="cast"`). A birthday is the month and day of
`person.birthday`, which is text like `"1986-05-13"` — so slice off the year (Topic 4.2) and compare.

In [12]:
df_cast = pd.json_normalize(data_shows, record_path="cast", meta=["id", "name"], meta_prefix="show.")
print(df_cast.shape)
df_cast[["show.name", "person.name", "person.birthday", "character.name"]].head()

(112, 22)

  show.name       person.name person.birthday     character.name
0     Girls       Lena Dunham      1986-05-13     Hannah Horvath
1     Girls  Allison Williams      1988-04-13    Marnie Michaels
2     Girls      Jemima Kirke      1985-04-26    Jessa Johansson
3     Girls       Zosia Mamet      1988-02-02  Shoshanna Shapiro
4     Girls       Adam Driver      1983-11-19       Adam Sackler

In [13]:
my_birthday = "05-13"          # MM-DD  <- change to your own

df_cast["birth_mmdd"] = df_cast["person.birthday"].str.slice(5)        # "1986-05-13" -> "05-13"
df_cast.loc[df_cast["birth_mmdd"] == my_birthday,
            ["person.name", "person.birthday", "character.name", "show.name"]]

   person.name person.birthday   character.name         show.name
0  Lena Dunham      1986-05-13   Hannah Horvath             Girls
8   Bea Arthur      1922-05-13  Dorothy Zbornak  The Golden Girls

In [14]:
# If nobody shares your birthday: which days ARE represented, and how many birthdays are missing?
print("missing birthdays:", df_cast["person.birthday"].isna().sum(), "of", len(df_cast))
df_cast["birth_mmdd"].value_counts().head()

missing birthdays: 41 of 112

birth_mmdd
07-13    4
05-13    2
04-15    2
08-29    2
01-30    2
Name: count, dtype: int64

**What the code does.**
- Each element of a show's `cast` list is `{"person": {...}, "character": {...}}`; flattening gives
  `person.name`, `person.birthday`, `character.name`, and so on — 112 rows.
- `.str.slice(5)` keeps characters from position 5 onward: `"1986-05-13"` → `"05-13"`. Comparing month-day
  ignores the birth year, which is what "share a birthday" means.
- `.loc[condition, columns]` filters rows and picks the columns to show in one step.

**Expected output (for May 13).** Two people: **Lena Dunham** (Hannah Horvath, *Girls*) and **Bea Arthur**
(Dorothy Zbornak, *The Golden Girls*). July 13 is the most common date in the data (4 rows).

**Common mistakes.**
- Comparing the full date (`== "1986-05-13"`) — that requires sharing the birth *year* too.
- Writing the day without zero-padding (`"5-13"`) → no matches; the data is `MM-DD` with leading zeros.
- 41 of 112 birthdays are missing (`NaN`), so "nobody shares my birthday" is common and not a bug — hence the
  question's "try a different day". `.str.slice` on `NaN` just returns `NaN`, and `NaN == "05-13"` is `False`, so
  no special handling is needed.
- Alternative that students who know datetimes may try: `pd.to_datetime(df_cast["person.birthday"])` then
  `.dt.month` / `.dt.day`. Equally correct, slightly more typing.

## TVMaze API

Now you will work with the [TVMaze API](http://www.tvmaze.com/api) from the reading. Use the API to request JSON data that you can use to answer the following questions.

1\. What was the longest show that aired in the U.S. on February 4, 2018?

_Hint:_ Use the ["Schedule" endpoint](http://www.tvmaze.com/api#schedule) to first get the data for all shows that aired on that date.

### Solution (TVMaze 1) — the longest show that aired on 4 February 2018

**Approach.** Read the documentation for the **Schedule** endpoint: `/schedule?country=US&date=2018-02-04`
returns a list of the *episodes* that aired that day, each with the `show` nested inside. One request, flatten,
sort by `runtime`.

In [15]:
import requests

response = requests.get("https://api.tvmaze.com/schedule",
                        params={"country": "US", "date": "2018-02-04"})
print(response.url)
print(response.status_code)

https://api.tvmaze.com/schedule?country=US&date=2018-02-04
200

In [16]:
# Processing lives in its own cell, so re-running it never re-requests
schedule = response.json()
print(type(schedule), len(schedule))
print(schedule[0].keys())

df_schedule = pd.json_normalize(schedule)
df_schedule.shape

<class 'list'> 41
dict_keys(['id', 'url', 'name', 'season', 'number', 'type', 'airdate', 'airtime', 'airstamp', 'runtime', 'rating', 'image', 'summary', 'show', '_links'])

(41, 62)

In [17]:
(df_schedule
 .sort_values("runtime", ascending=False)
 [["show.id", "show.name", "name", "airtime", "runtime", "show.network.name"]]
 .head())

,show.id,show.name,name,airtime,runtime,show.network.name
23,6011,Super Bowl,Super Bowl LII - New England Patriots vs. Phil...,18:30,210,ABC
29,1195,Alaska: The Last Frontier,The Blind Side,20:00,180,Discovery
21,17584,This Week in Tech,We're All Out of Kidneys,17:15,120,NaN
19,6821,Puppy Bowl,Puppy Bowl XIV,15:00,120,Animal Planet
27,89260,Kasie DC,Episode 5,19:00,120,MS NOW

**What the code does.**
- `params={...}` — `requests` builds the query string; `response.url` shows the result
  (`...schedule?country=US&date=2018-02-04`), which is worth printing so students see what was actually asked.
- `status_code` 200 = success. Check it *before* `.json()`; a failed request often still has a body, and
  `.json()` on an error page is a confusing way to find out.
- Each element of the reply is an **episode** with keys like `name`, `airtime`, `runtime`, and `show` (a nested
  dictionary). After flattening, the episode's own fields keep their names and the show's fields become
  `show.id`, `show.name`, `show.network.name`, … (41 rows × ~60 columns).
- `sort_values("runtime", ascending=False)` puts the longest broadcast first.

**Expected output.** **Super Bowl LII — New England Patriots vs. Philadelphia Eagles**, `runtime` = **210
minutes**, 18:30. Next: *Alaska: The Last Frontier* (180), then several 120-minute programmes.

**Common mistakes.**
- Date format: the API wants ISO `YYYY-MM-DD`. `"02-04-2018"` or `"2/4/2018"` returns an error or an empty list.
- Leaving out `country=US`: the endpoint then defaults to US today, but students who pass another country
  code get a different (valid-looking) answer.
- Sorting by `show.runtime` instead of `runtime`. `show.runtime` is the show's *typical* length (Puppy Bowl:
  typical 180, but that day's broadcast ran 120); `runtime` is the length of *this airing*. The question is
  about what aired that day. The top answer is the same either way here, but the ranking below it is not.
- Reading the question as "longest-running series" — it is about duration in minutes.
- Building the URL by hand with a typo (`?country=US?date=...`); passing `params` avoids this entirely.

2\. Among all shows that aired in the U.S. on Feburary 4, 2018, which non-voice actors appeared on more than one show? Note: some people are credited with multiple rows on the same show and thus appear as multiple rows in the data frame.

Hint: You will need to write a for loop to make multiple requests. Use the "show.id" from the data from part 1, and use the ["Shows" endpoint](http://www.tvmaze.com/api#show-cast) to get the cast of each show. Don't forget to stagger your requests, or you will be blocked by the website!

### Solution (TVMaze 2) — non-voice actors on more than one show

**Approach.** The schedule tells us *which shows* aired; the cast lives at a different endpoint,
`/shows/{id}/cast`, **one show per request**. So: collect the distinct show ids → loop, one request each,
pausing between requests → tag each cast record with its show → flatten once → filter to non-voice →
count **distinct shows** per person.

In [18]:
show_ids = df_schedule["show.id"].unique()
len(show_ids)             # 41 airings, but some shows aired twice -> fewer distinct shows

38

In [19]:
import time

# REQUEST CELL — run once. ~40 requests with a half-second pause takes under a minute.
cast_records = []
for show_id in show_ids:
    response = requests.get(f"https://api.tvmaze.com/shows/{show_id}/cast")
    if response.status_code != 200:                 # don't let one bad reply poison the list
        print("skipped", show_id, "status", response.status_code)
        continue
    members = response.json()                       # a list of {"person":..., "character":..., "self":..., "voice":...}
    for member in members:
        member["show_id"] = int(show_id)            # the cast endpoint does NOT say which show -> tag it ourselves
    cast_records.extend(members)                    # extend = add each member; append would add one list
    time.sleep(0.5)                                 # stagger the requests (TVMaze allows ~20 per 10 seconds)

len(cast_records)

878

In [20]:
# PROCESSING CELL — safe to re-run as often as you like
df_cast_day = pd.json_normalize(cast_records)
print(df_cast_day.shape)
print(df_cast_day["voice"].value_counts())
df_cast_day[["show_id", "person.id", "person.name", "character.name", "voice", "self"]].head()

(878, 25)
voice
True     692
False    186
Name: count, dtype: int64

   show_id  person.id        person.name character.name  voice  self
0     7795     117627  Johnny Devenanzio           Host  False  True
1     7795     132602         Angela Sun           Host  False  True
2     7795      71115     Ashley Roberts           Host  False  True
3     7795      51988   Audrina Patridge           Host  False  True
4     7795     235612      Pedro Andrade           Host  False  True

In [21]:
non_voice = df_cast_day[~df_cast_day["voice"]]                    # keep rows where voice is False

shows_per_person = (non_voice
                    .groupby(["person.id", "person.name"])["show_id"]
                    .nunique()                                     # DISTINCT shows, not rows
                    .sort_values(ascending=False))
repeat_people = shows_per_person[shows_per_person > 1]
repeat_people

person.id  person.name
162299     Tom Llamas        2
102424     John Dickerson    2
Name: show_id, dtype: int64

In [22]:
# Which shows? Bring the show names back in from the schedule (a Week 3 merge)
show_names = df_schedule[["show.id", "show.name"]].drop_duplicates()

(non_voice[non_voice["person.id"].isin(repeat_people.index.get_level_values("person.id"))]
 .merge(show_names, left_on="show_id", right_on="show.id")
 [["person.name", "character.name", "self", "show.name"]]
 .drop_duplicates()
 .sort_values("person.name"))

,person.name,character.name,self,show.name
0,John Dickerson,Contributor,True,CBS News Sunday Morning
1,John Dickerson,Host & Moderator,True,Face the Nation
2,Tom Llamas,Anchor,True,ABC World News Tonight with David Muir
3,Tom Llamas,Anchor,True,NBC Nightly News

**What the code does.**
- `.unique()` — 41 airings come from 38 distinct shows; requesting a show's cast twice would waste requests
  *and* double-count its cast.
- The f-string `f".../shows/{show_id}/cast"` builds a different URL on each pass of the loop. Here the varying
  part is in the **path**, not a `?parameter`, so `params=` is not used.
- **Tagging**: the reply contains people and characters but no show id. Adding `member["show_id"] = ...`
  *before* `extend` is what makes the final question answerable. (`int(...)` converts numpy's integer type to a
  plain Python one.)
- `extend` vs `append`: `extend` adds the *elements* of the reply to our list (a flat list of cast members —
  what `json_normalize` wants). `append` would give a list of 38 lists.
- `time.sleep(0.5)` — the "stagger" the hint demands. TVMaze's limit is about 20 calls per 10 seconds; without a
  pause you get HTTP **429** (Too Many Requests) and, if you persist, a temporary block.
- `~df["voice"]` — `voice` is already `True`/`False`; `~` flips it, keeping non-voice credits.
- `.nunique()` counts **distinct** shows per person. This is the question's warning in code: a person credited
  twice on the *same* show (two characters) has 2 rows but 1 show.
- Grouping by `person.id` as well as the name guards against two different people with the same name.

**Expected output.** 38 shows → about 880 cast rows, roughly 690 of them voice credits (the day's schedule is
full of animation: *The Simpsons*, *Family Guy*, *Bob's Burgers*, …). Among ~186 non-voice credits, two people
appear on more than one show: **Tom Llamas** and **John Dickerson** — news anchors, credited as themselves
(`self == True`) on Sunday news programmes.

**Common mistakes.**
- **No `time.sleep`** → a burst of 429 responses; then `response.json()` returns an error dictionary rather than a
  list, and `extend` quietly adds its *keys* (strings) to the list, so `json_normalize` fails much later with a
  baffling message. The `status_code` check above prevents that.
- **`.size()` / `.count()` / `value_counts()` on names** instead of `nunique()` on shows → a long list of false
  positives: every actor who plays two characters on one show.
- **Forgetting to tag the show** → all the cast in one frame and no way to count shows. Students usually
  discover this only at the groupby; point them back to the loop.
- **Requests and processing in one cell** → every pandas typo costs another 40 requests. Split them.
- Looping over `df_schedule["show.id"]` without `.unique()` → duplicate requests and inflated counts.
- Filtering with `df["voice"] == "False"` (a string) → nothing matches; it is a Boolean.
- Students may ask whether "actors" should exclude people appearing as themselves. The question only says
  non-voice, so the two anchors are the intended answer; adding `& ~df["self"]` leaves nobody, which is a nice
  discussion of how the definition drives the answer.

# Tasty API

[Tasty.co](http://tasty.co) is a website and app that offers food recipes. They have made these recipes available through a [a REST API](https://rapidapi.com/apidojo/api/tasty). However, unlike the TVMaze API, this one requires authentication.

Specifically, you will need to create an account and subscribe to the "Basic" (free) plant. You will then be provided with an API key (X-Rapid-API-Key) that will need to be supplied with every request you make. This is used to track and limit usage.

1. [create an account](https://rapidapi.com/apidojo/api/tasty) and subscribe to the "Basic" (free) plan
2. log in and copy the X-RapidAPI-Key, which is a long string of letters and digits
3. paste this key to replace "PUT-YOUR-KEY-HERE" in the `headers` below

If you did everything correctly, then running the cell below should return a JSON object containing all the tags recognized by the Tasty API.

> **Instructor note — how this section was run.** The key is read from the environment variable
> `RAPIDAPI_KEY` so that it never appears in the notebook (`export RAPIDAPI_KEY=...` before launching Jupyter,
> or before running `tools/build_week5_pas.py`). **If no key is set, the cells below run on a small MOCK** that
> imitates the structure of the API's reply (`count` + `results`, with `price`, `user_ratings`, and `tags`
> inside each recipe). The mock's recipes and numbers are **invented for illustration** — they are not Tasty
> data — so use the *code and explanations* in class, and rebuild with a key for real answers. The banner
> printed by the next cell says which mode was used.

In [23]:
import os
import time
import requests

domain = "https://tasty.p.rapidapi.com"

API_KEY = os.environ.get("RAPIDAPI_KEY", "PUT-YOUR-KEY-HERE")
USE_LIVE = API_KEY != "PUT-YOUR-KEY-HERE"

headers = {
    "X-RapidAPI-Key": API_KEY,
    "X-RapidAPI-Host": "tasty.p.rapidapi.com",
}

print("MODE:", "LIVE Tasty API" if USE_LIVE else "MOCK data (no RAPIDAPI_KEY set) — numbers below are illustrative only")

MODE: MOCK data (no RAPIDAPI_KEY set) — numbers below are illustrative only

In [24]:
# MOCK replies — same shape as the real API, invented values. Used only when no key is available.
def _recipe(i, name, portion, pos, neg, tags):
    return {"id": i, "name": name, "num_servings": 4,
            "price": {"total": portion * 4, "portion": portion},
            "user_ratings": {"count_positive": pos, "count_negative": neg,
                             "score": round(pos / (pos + neg), 6) if pos + neg else None},
            "tags": [{"id": 1000 + k, "name": t, "display_name": t.replace("_", " ").title(), "type": "mock"}
                     for k, t in enumerate(tags)]}

MOCK_DAIKON = {"count": 4, "results": [
    _recipe(101, "(mock) Pickled Daikon", 75, 310, 22, ["vegetarian", "vegan", "sides"]),
    _recipe(102, "(mock) Daikon Noodle Soup", 260, 120, 9, ["dinner", "asian"]),
    _recipe(103, "(mock) Banh Mi With Daikon Slaw", 410, 980, 61, ["lunch", "sandwiches"]),
    _recipe(104, "(mock) Daikon Cake", 0, 12, 1, ["vegetarian", "snacks"]),          # price 0 = unknown
]}

MOCK_AVOCADO = {"count": 6, "results": [
    _recipe(201, "(mock) Avocado Toast", 180, 2400, 130, ["vegetarian", "breakfast"]),
    _recipe(202, "(mock) Chicken Avocado Wrap", 390, 820, 95, ["lunch"]),
    _recipe(203, "(mock) Guacamole", 120, 5100, 140, ["vegetarian", "vegan", "appetizers"]),
    _recipe(204, "(mock) Avocado Brownies", 95, 3, 0, ["vegetarian", "desserts"]),      # tiny sample, 100% positive
    _recipe(205, "(mock) Shrimp Avocado Salad", 450, 640, 38, ["dinner", "seafood"]),
    {"id": 206, "name": "(mock) Avocado Compilation", "user_ratings": {"count_positive": 0, "count_negative": 0}},
]}

In [25]:
# The activity's connection test: list the tags the API recognises
if USE_LIVE:
    response = requests.get(f"{domain}/tags/list", headers=headers)
    print(response.status_code)
    tags_json = response.json()
    print(tags_json.keys(), "|", tags_json["count"], "tags")
else:
    print("skipped (mock mode). With a valid key this prints 200 and a dictionary with keys 'count' and 'results'.")
    print("Without a valid key the API answers 401/403 and a JSON message such as 'You are not subscribed to this API.'")

skipped (mock mode). With a valid key this prints 200 and a dictionary with keys 'count' and 'results'.
Without a valid key the API answers 401/403 and a JSON message such as 'You are not subscribed to this API.'

You will need to pass these `headers` with every HTTP request to the API. The API key (X-RapidAPI-Key) is how the server keeps track of how many requests you have made.

Take a look at [the documentation](https://rapidapi.com/apidojo/api/tasty). We will use the recipes/list endpoint.

Make sure you are logged into the account you are created, and select the recipes/list endpoint from the menu at left. Notice that this brings up a form that you can fill in, which generates the corresponding code.  By default, it provides Node.js code; change this to Python with the Requests client.

1\. Search for recipes containing "daikon" (an Asian radish) and request the JSON data, and convert it to a Pandas data frame.

### Solution (Tasty 1) — daikon recipes to a data frame

**Approach.** Same request pattern as TVMaze, with two additions: the **`headers`** carry the key, and the
search term goes in `params` (`q`). The reply is a **dictionary** with two keys — `count` (how many recipes
match in total) and `results` (this page of recipes) — so flatten `["results"]`, not the whole reply.

In [26]:
if USE_LIVE:
    response = requests.get(f"{domain}/recipes/list", headers=headers,
                            params={"from": 0, "size": 40, "q": "daikon"})
    print(response.status_code)
    daikon_json = response.json()
else:
    daikon_json = MOCK_DAIKON                      # stand-in with the same structure — NOT real Tasty data

print(daikon_json.keys())
df_daikon = pd.json_normalize(daikon_json["results"])
df_daikon.shape

dict_keys(['count', 'results'])

(4, 9)

In [27]:
df_daikon[["id", "name", "price.portion", "user_ratings.count_positive", "user_ratings.count_negative"]].head()

,id,name,price.portion,user_ratings.count_positive,user_ratings.count_negative
0,101,(mock) Pickled Daikon,75,310,22
1,102,(mock) Daikon Noodle Soup,260,120,9
2,103,(mock) Banh Mi With Daikon Slaw,410,980,61
3,104,(mock) Daikon Cake,0,12,1

**What the code does.**
- `headers=headers` must accompany **every** request to this API; that is how RapidAPI knows whose quota to
  charge. `params` are the search options from the documentation form: `from` (offset of the first result),
  `size` (results per page, maximum 40), `q` (search text).
- `daikon_json.keys()` → `count` and `results`. `results` is the list of recipes, and `json_normalize` wants a
  list of records — so pass `daikon_json["results"]`.
- Nested dictionaries inside a recipe flatten to dotted names: `price.portion`, `user_ratings.count_positive`, …
  Nested **lists** (`tags`, `sections`, `instructions`) stay as lists in a single cell — that is what Tasty 5 is about.

**Common mistakes.**
- `pd.json_normalize(response.json())` without `["results"]` → a **one-row** frame with columns `count` and
  `results`. One row is the giveaway.
- HTTP **401/403** with a message such as "You are not subscribed to this API": the key is fine but the student
  never clicked *Subscribe* on the Basic plan — or pasted the key with a stray space/quote. **429** means the
  monthly free quota is used up (it is small — another reason to separate request cells from processing cells).
- Leaving `headers` off the second and later requests.
- **Posting the key**: a notebook pushed to GitHub or shared in a forum exposes it. In this notebook the key is
  read from an environment variable for exactly that reason.

2\. How many recipes containing daikon are there? Which one is the cheapest per portion?

### Solution (Tasty 2) — how many daikon recipes, and the cheapest per portion

**Approach.** "How many" is the API's own `count` (compare it with the number of rows actually received).
"Cheapest per portion" is a sort on `price.portion` — after removing recipes with no price.

In [28]:
print("API says:", daikon_json["count"], "| rows received:", len(df_daikon))

API says: 4 | rows received: 4

In [29]:
priced = df_daikon[df_daikon["price.portion"] > 0]              # drop missing (NaN) and zero prices
print(len(priced), "of", len(df_daikon), "recipes have a per-portion price")

priced.sort_values("price.portion")[["name", "price.portion", "price.total", "num_servings"]].head()

3 of 4 recipes have a per-portion price

                              name  price.portion  price.total  num_servings
0            (mock) Pickled Daikon             75          300             4
1        (mock) Daikon Noodle Soup            260         1040             4
2  (mock) Banh Mi With Daikon Slaw            410         1640             4

**What the code does.**
- `count` is the total number of matches on the server; `len(df_daikon)` is how many came back in *this* reply.
  They agree only when the total fits in one page (≤ 40). That distinction is the entire reason for the loop in
  the next question.
- `df["price.portion"] > 0` is `False` for `NaN`, so this one filter removes both the recipes with no price
  information and any recorded as 0.
- `sort_values("price.portion")` ascending → cheapest first. Prices appear to be recorded in **US cents**
  (e.g. `250` = $2.50) — worth saying aloud, since "250" looks expensive for a portion.

**Common mistakes.**
- Answering with `len(df_daikon)` when `count` is larger than 40 — the frame only holds the first page.
- Sorting without filtering: a recipe with price 0 (or `NaN`, which sorts last but confuses `idxmin` users
  less than zeros do) is reported as "cheapest".
- Using `price.total` (the whole dish) when the question asks **per portion**.
- `KeyError: 'price.portion'` — if *no* recipe in the reply has a `price` object the column is never created;
  check `df_daikon.columns`.

3\. Find recipes containing avocado and request the JSON data.

**Hint:** Note that there are hundreds of results, but the API only returns 20 results by default and only 40 results maximum, even if you specify the `size=` parameter, so you will need to use a `for` loop, incrementing the `from=` parameter. Be sure to respect the API's rate limits (or you may be blocked!)

**Note:** Recall from the example in the reading that we created an empty list `episodes = []` and then added the results of each request to it in the for loop with `episodes.extend(response.json())`. But note that in the recipes/list endpoint there are two keys: count and results. We only want the results so try instead `.extend(response.json()).get("results")`.

**Suggestion:** Try writing a loop that only makes 2 or 3 requests first so you can test that it's working correctly. Also, make sure you use separate cells for code that makes requests to the API versus processing of the results; you don't want to rerun the requests unless absolutely necessary!

### Solution (Tasty 3) — all the avocado recipes (pagination)

**Approach.** There are hundreds of matches but at most 40 per reply, so request **pages**: `from=0`, `from=40`,
`from=80`, … The first reply's `count` tells us where to stop. Collect only each reply's `results`.

⚠️ **The hint in the activity has a typo.** It shows `.extend(response.json()).get("results")`. The parentheses
are in the wrong place: that extends the list with the reply *dictionary* (which adds its **keys**, the strings
`"count"` and `"results"`), and then calls `.get` on `None` (the return value of `extend`) →
`AttributeError: 'NoneType' object has no attribute 'get'`. The correct form is
**`.extend(response.json().get("results"))`**. Expect several students to paste the hint verbatim.

In [30]:
PAGE_SIZE = 40

if USE_LIVE:
    # REQUEST CELL — run once. First request also tells us the total.
    first = requests.get(f"{domain}/recipes/list", headers=headers,
                         params={"from": 0, "size": PAGE_SIZE, "q": "avocado"}).json()
    total = first["count"]
    avocado = list(first["results"])

    for start in range(PAGE_SIZE, total, PAGE_SIZE):            # 40, 80, 120, ...
        response = requests.get(f"{domain}/recipes/list", headers=headers,
                                params={"from": start, "size": PAGE_SIZE, "q": "avocado"})
        if response.status_code != 200:
            print("stopped at", start, "status", response.status_code)
            break
        avocado.extend(response.json().get("results"))          # only the recipes, not the wrapper
        time.sleep(1)                                           # respect the rate limit
else:
    total = MOCK_AVOCADO["count"]
    avocado = list(MOCK_AVOCADO["results"])                     # stand-in — NOT real Tasty data

print("API count:", total, "| recipes collected:", len(avocado))

API count: 6 | recipes collected: 6

In [31]:
# PROCESSING CELL
df_avocado = pd.json_normalize(avocado).drop_duplicates(subset="id")
df_avocado.shape

(6, 9)

**What the code does.**
- `range(PAGE_SIZE, total, PAGE_SIZE)` generates the offsets 40, 80, 120, … up to (not including) `total`; with
  the first page already in hand, that covers every recipe with no wasted request.
- `response.json().get("results")` — `.get("results")` is the dictionary method, the same as `["results"]` except
  that it returns `None` instead of raising an error if the key is missing.
- `avocado.extend(...)` grows **one flat list of recipe dictionaries** across all pages — the shape
  `json_normalize` needs.
- `time.sleep(1)` between requests; the `status_code` check stops the loop cleanly if the quota runs out
  rather than filling the list with error messages.
- `drop_duplicates(subset="id")`: results can shift between pages while you are paging, so a recipe
  occasionally arrives twice.

**Teaching suggestion (from the activity, and worth repeating):** first run the loop for 2–3 pages only —
`range(PAGE_SIZE, 3 * PAGE_SIZE, PAGE_SIZE)` — and check `len(avocado)` is 120 and the first names differ page to
page. Only then run the full loop. Every request counts against a small monthly quota.

**Common mistakes.**
- The hint's misplaced parenthesis (above).
- `append` instead of `extend` → a list of lists; `json_normalize` then produces nonsense columns `0, 1, 2, …`.
- Forgetting to change `from` inside the loop (a constant `params`) → the same 40 recipes, many times over;
  `drop_duplicates` exposes it (shape collapses to 40 rows).
- Asking for `size=100`: the API silently caps at 40, so stepping by 100 **skips** 60 recipes per page.
- Re-running the request cell to fix a pandas error → quota gone. Keep processing in a separate cell.

4\. For the recipes containing avocado, compute the proportion of reviews that are positive. For the avocado recipes with over 500 reviews, which one has the highest proportion of positive reviews?

### Solution (Tasty 4) — proportion of positive reviews

**Approach.** Each recipe has `user_ratings.count_positive` and `user_ratings.count_negative`. The proportion
is positive ÷ (positive + negative). Then filter to recipes with more than 500 reviews in total and sort.

In [32]:
df_avocado["n_reviews"] = (df_avocado["user_ratings.count_positive"]
                           + df_avocado["user_ratings.count_negative"])
df_avocado["prop_positive"] = df_avocado["user_ratings.count_positive"] / df_avocado["n_reviews"]

df_avocado[["name", "user_ratings.count_positive", "user_ratings.count_negative",
            "n_reviews", "prop_positive"]].head()

,name,user_ratings.count_positive,user_ratings.count_negative,n_reviews,prop_positive
0,(mock) Avocado Toast,2400,130,2530,0.948617
1,(mock) Chicken Avocado Wrap,820,95,915,0.896175
2,(mock) Guacamole,5100,140,5240,0.973282
3,(mock) Avocado Brownies,3,0,3,1.000000
4,(mock) Shrimp Avocado Salad,640,38,678,0.943953

In [33]:
(df_avocado[df_avocado["n_reviews"] > 500]
 .sort_values("prop_positive", ascending=False)
 [["name", "n_reviews", "prop_positive"]]
 .head())

                          name  n_reviews  prop_positive
2             (mock) Guacamole       5240       0.973282
0         (mock) Avocado Toast       2530       0.948617
4  (mock) Shrimp Avocado Salad        678       0.943953
1  (mock) Chicken Avocado Wrap        915       0.896175

**What the code does.**
- Column arithmetic is element-wise: one proportion per recipe.
- A recipe with no reviews gives 0 / 0 = `NaN` (pandas does not raise an error). Those rows then fail the
  `> 500` filter on their own, so no special handling is needed — but students should know why `NaN`s appear.
- The 500-review threshold is the statistical point of the question: a recipe with 3 reviews, all positive,
  has a proportion of 1.0 and would otherwise "win". Small samples make extreme proportions.
- The API also supplies `user_ratings.score`, which is this same proportion — a handy check on the arithmetic.

**Common mistakes.**
- Dividing by `count_positive` alone, or by `count_negative` → proportions above 1.
- Filtering on `count_positive > 500` rather than on the **total** number of reviews.
- Sorting first and reading the top row *before* applying the 500 filter → a recipe with a handful of reviews.
- Reporting `idxmax()` (a row label) rather than the recipe's name.

5\. Take the avocado JSON data from above (you do NOT need to read in the data from the REST API again). How many recipes are vegetarian? You should be able to identify this from the "tags" attribute.

Hint: Try using `json_normalize` with "tags" as the record path to flatten the data so that there is one row for each tag.

### Solution (Tasty 5) — how many avocado recipes are vegetarian?

**Approach.** `tags` is a **list of dictionaries** inside each recipe, so change the unit of the row to the
**tag**: `record_path="tags"`, keeping the recipe's `id` and `name` as `meta`. Then filter the tag rows to
`vegetarian` and count **distinct recipes**. No new API requests — this reuses the `avocado` list.

In [34]:
with_tags = [recipe for recipe in avocado if recipe.get("tags")]       # a few items have no tags list
print(len(avocado) - len(with_tags), "items without tags skipped")

df_tags = pd.json_normalize(with_tags, record_path="tags",
                            meta=["id", "name"], meta_prefix="recipe.")
print(df_tags.shape)
df_tags.head()

1 items without tags skipped
(10, 6)

     id        name display_name  type recipe.id                  recipe.name
0  1000  vegetarian   Vegetarian  mock       201         (mock) Avocado Toast
1  1001   breakfast    Breakfast  mock       201         (mock) Avocado Toast
2  1000       lunch        Lunch  mock       202  (mock) Chicken Avocado Wrap
3  1000  vegetarian   Vegetarian  mock       203             (mock) Guacamole
4  1001       vegan        Vegan  mock       203             (mock) Guacamole

In [35]:
vegetarian = df_tags[df_tags["name"] == "vegetarian"]
n_vegetarian = vegetarian["recipe.id"].nunique()
print(n_vegetarian, "of", df_avocado["id"].nunique(), "avocado recipes are tagged vegetarian")

3 of 6 avocado recipes are tagged vegetarian

**What the code does.**
- `record_path="tags"` → one row per (recipe, tag) pair; a recipe with 12 tags contributes 12 rows. Each tag has
  its own `id`, `name` (machine name, e.g. `vegetarian`), `display_name`, and `type` (e.g. `dietary`).
- `meta=["id", "name"]` with `meta_prefix="recipe."` — again essential, because tags *also* have `id` and
  `name`. In `df_tags`, `name` is the **tag's** name and `recipe.name` is the recipe's.
- The list comprehension drops items with no `tags` (the search can return *compilations* as well as recipes);
  `json_normalize` raises `KeyError: 'tags'` if any record lacks the key.
- `.nunique()` on the recipe id counts recipes, not rows — robust even if a duplicate slipped through.

**Common mistakes.**
- `KeyError: "Key 'tags' not found"` → a record without tags; filter first, as above.
- `ValueError: Conflicting metadata name id` → missing `meta_prefix` (same fix as Shows 2).
- Filtering `df_tags["recipe.name"].str.contains("vegetarian")` — that searches recipe *titles*, and misses most
  vegetarian recipes.
- `str.contains("veg")` on the tag name also matches `vegan` and `vegetables` style tags; use `==`. (Whether
  vegan recipes should count as vegetarian is a fair discussion — in practice Tasty tags vegan recipes with
  both.)
- Counting rows of `df_tags` and calling it the number of recipes.
- Going back to the API for this question. The instruction says not to: the data is already in `avocado`.